<?php

namespace Forumhouse\LaravelAmqp\Jobs;

/**
 * Interface IAMQPJobBase
 *
 * THIS INTERFACE MUST BE IMPLEMENTED BY ANY JOB THAT WOULD LIKE TO USE AMQP;
 * IN A LOT OF OTHER DRIVERS (E.G. BEANSTALKD), ATTEMPTS ARE MANAGED BY THE QUEUE SERVER ITSELF.
 * HOWEVER AMQP IS NOT AWARE OF ATTEMPTS (I.E. IT IS UP TO THE CONSUMER). AS A RESULT, THE ATTEMPTS COUNT MUST BE
 * STORED AS STATE IN THE PAYLOAD.
 *
 * THIS INTERFACE EXTENDS THE CLASSIC LARAVEL JOB, TO ALSO SUPPORT ATTEMPTS (SO THAT LARAVEL MAY PERFORM ERROR-HANDLING)
 * AND PRIORITY (IF NEEDED)
 *
 *
 * UNFORTUNATELY, THIS DOES MEAN THAT ALL LARAVEL JOBS THAT WANT TO USE AMQP MUST IMPLEMENT THIS INTERFACE.
 *
 * @package Forumhouse\LaravelAmqp\Jobs
 */
interface IAMQPJobBase
{
	/** @return int | null */
    public function getAttempts();
    public function setAttempts($i);

	/**
	 * PRIORITY IS AN OPTIONAL FEATURE OF AMQP,
	 * IF YOU DON'T NEED PRIORITY, SIMPLY IMPLEMENT THE GETTER AND RETURN NULL.
	 *
	 * @return int | null
	 */
	public function getPriority();
}
